### ISSUE TITLE
As a patient I need to have my interactions logged so that I can help make the app better.

### ISSUE THREAD

**Issue by adphillips2017** [cns-iu/spoke-vis#16]
Ensure the patient has their interactions logged in order to help make the app better by providing:

- [ ]  A database that collects click information

**Comment by bherr2** [comment]
Here is feedback / guidance on what to log from Katy:

Web interface
* [ ] Click on any links
* [ ] Selection in pull-down menu

Overview network
* [ ] Click on any node or link to see data
* [ ] Pick one of 3 diseases
* [ ] Pick one of 800 food items

![](https://lh4.googleusercontent.com/CN93642oQllW3vH2D5mpeYC77CMAhbz212fHeRrfW_1uFYgTSEOJCgiKNjRJJi9TNEbbud92MpulH24XMz3Jc1XFqMDDrWz0xulf6hc_TxM-ShPriGC17C5onntxJV723mBaiT02)

Details network

* [ ] Click on any node or link to see data
* [ ] Zoom, pan

![](https://lh6.googleusercontent.com/wdNG9AKQBttW28E_-xK3KengQQiXi54-54QEbpNhtJLxwWj8J14PNWrtt07EQy-CH1rwGjDpmdbIXNDNlr-sq3xQ71xwu9DafSrj1L3BvV_mRhbUC6Tqk91NG7jeVE3XBb85uqD0)

![](https://lh3.googleusercontent.com/DXygXBCQL7-1h60XnVAt0xfNux7IXtICiyu_dVnIW_BtLbslrH4FvfMKphpdPzLzSbqoT4j9alUkwULfJkX8wG1GY0VMiCQ1n37bqVTcjqxUfpYeE5FLJYBseBPLW4GB8cwQyrb1)

Raw data
* [ ] Mouse pointer--get heatmap

Derived 
* [ ] time-stamps--durations.

Research Qs (just a heads up)
* Can users read/remember the map layout?
* Can they read 1 map and transfer expertise to next map
* Understanding zoom levels

Tasks
* Find specific nodes, edges
* Identify pathways

Control Group?
* Compare different UIs - search result list vs. food map areas

Likely misconceptions:
* All green areas are similar
* No labels in areas--areas are unimportant

Possible problems
* Overlapping labels
