### ISSUE TITLE
Change "Go to SPOKE" label

### ISSUE THREAD

**Issue by bherr2** [cns-iu/spoke-vis#42]
@lecross can you provide the better label for the button?

**Comment by lecross** [comment]
OK, what I found is that Katy called it the Network Visualizer. So SPOKE Network Visualizer. Wasn't where I thought. If you look at the charter under goals, that's where it is. Not really a formal product name, but seems to work for now. Will need to be cleared with Katy of course. I'd actually shorten to SPOKE Visualizer to allow for flexibility.

**Comment by bherr2** [comment]
Done
